#!/usr/bin/env python3
"""
build_site.py — Extracts data from the old bloated HTML, fixes timestamps,
and writes a clean data.js for use with index.html.

Usage:
    python3 build_site.py

Output:
    data.js  (in the same directory as this script)
"""
import re, json, datetime
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
SOURCE_HTML = SCRIPT_DIR.parent.parent.parent / "FYUGP_Dashboard" / "Backup_FYUGP Tracker Part-1" / "RawDataOnFYUGPImplementation" / "FYUGP Tracker Index.html"
OUTPUT_JS = SCRIPT_DIR / "data.js"


def extract_balanced(text, start_pos):
    """Extract a balanced {}/[] block starting at start_pos."""
    open_char = text[start_pos]
    close_char = '}' if open_char == '{' else ']'
    depth = 0
    for i in range(start_pos, len(text)):
        if text[i] == open_char:
            depth += 1
        elif text[i] == close_char:
            depth -= 1
            if depth == 0:
                return text[start_pos:i + 1]
    return None


def js_to_json(js_str):
    """Convert a JS object string to valid JSON by quoting unquoted keys and removing trailing commas."""
    # Quote unquoted property names: word: → "word":
    fixed = re.sub(r'([{,]\s*)(\w+)(\s*:)', r'\1"\2"\3', js_str)
    # Remove trailing commas before } or ]
    fixed = re.sub(r',\s*([}\]])', r'\1', fixed)
    return fixed


def main():
    if not SOURCE_HTML.exists():
        print(f"ERROR: Source HTML not found at {SOURCE_HTML}")
        return

    html = SOURCE_HTML.read_text(encoding="utf-8")
    today = datetime.date.today().isoformat()

    # ── Extract PORTALS object using bracket matching ──
    portals_start = html.find('const PORTALS')
    if portals_start == -1:
        print("ERROR: Could not find PORTALS in source HTML")
        return
    brace_start = html.find('{', portals_start)
    portals_str = extract_balanced(html, brace_start)
    if not portals_str:
        print("ERROR: Could not extract PORTALS object")
        return
    # Convert JS object to valid JSON
    portals_json_str = js_to_json(portals_str)
    portals = json.loads(portals_json_str)

    # ── Extract FYUGP_DATA array using bracket matching ──
    data_start = html.find('const FYUGP_DATA')
    if data_start == -1:
        print("ERROR: Could not find FYUGP_DATA in source HTML")
        return
    bracket_start = html.find('[', data_start)
    data_str = extract_balanced(html, bracket_start)
    if not data_str:
        print("ERROR: Could not extract FYUGP_DATA array")
        return

    try:
        data = json.loads(data_str)
    except json.JSONDecodeError as e:
        print(f"ERROR: Could not parse FYUGP_DATA as JSON: {e}")
        return

    # ── Fix timestamps ──
    fixes = 0
    for record in data:
        if record.get("last_updated", "").startswith("2026"):
            record["last_updated"] = today
            fixes += 1

        for article in record.get("articles", []):
            d = article.get("date", "")
            if "2026" in d:
                article["date"] = d.replace("2026", "2025")
                fixes += 1
            t = article.get("title", "")
            if "2026" in t:
                article["title"] = t.replace("2026", "2025")
                fixes += 1

        s = record.get("summary", "")
        if "2026" in s:
            record["summary"] = s.replace("2026", "2025")
            fixes += 1

        ny = record.get("notified_year", "")
        if ny == "2026":
            record["notified_year"] = "2025"
            fixes += 1

    # ── Write data.js ──
    with open(OUTPUT_JS, "w", encoding="utf-8") as f:
        f.write("// FYUGP Tracker Data — auto-generated by build_site.py\n")
        f.write(f"// Generated: {today}\n")
        f.write(f"// Records: {len(data)} states/UTs\n\n")
        f.write(f"const PORTALS = {json.dumps(portals, indent=2)};\n\n")
        f.write(f"const FYUGP_DATA = {json.dumps(data, indent=2)};\n")

    print(f"✓ data.js written to {OUTPUT_JS}")
    print(f"  - {len(data)} state/UT records")
    print(f"  - {fixes} timestamp fixes applied (2026 → current year/2025)")
    print(f"  - File size: {OUTPUT_JS.stat().st_size:,} bytes")


if __name__ == "__main__":
    main()
