// FYUGP Tracker Data — auto-generated by build_data.py
// Generated: 2026-08-17
// Records: 36 states/UTs

const PORTALS = {
  "Andhra Pradesh": {
    "label": "AP State Higher Education Council",
    "url": "https://apshec.ap.gov.in/"
  },
  "Arunachal Pradesh": {
    "label": "Rajiv Gandhi University",
    "url": "https://www.rgu.ac.in/"
  },
  "Assam": {
    "label": "Directorate of Higher Education, Assam",
    "url": "https://dhe.assam.gov.in/"
  },
  "Bihar": {
    "label": "Bihar State Higher Education Council",
    "url": "https://bshec.bihar.gov.in/"
  },
  "Chandigarh": {
    "label": "Panjab University, Chandigarh",
    "url": "https://www.puchd.ac.in/"
  },
  "Chhattisgarh": {
    "label": "Chhattisgarh Higher Education Department",
    "url": "https://highereducation.cg.gov.in/"
  },
  "Delhi": {
    "label": "University of Delhi",
    "url": "https://www.du.ac.in/"
  },
  "Goa": {
    "label": "Directorate of Higher Education, Goa",
    "url": "https://dhe.goa.gov.in/"
  },
  "Gujarat": {
    "label": "Gujarat Education Department",
    "url": "https://gujarat-education.gov.in/"
  },
  "Haryana": {
    "label": "Higher Education Haryana",
    "url": "https://highereducationharyana.org/"
  },
  "Himachal Pradesh": {
    "label": "HP Higher Education Directorate",
    "url": "https://dhehp.nic.in/"
  },
  "Jammu & Kashmir": {
    "label": "University of Kashmir",
    "url": "https://www.kashmiruniversity.net/"
  },
  "Jharkhand": {
    "label": "Jharkhand State HE Council",
    "url": "https://jshec.jharkhand.gov.in/"
  },
  "Karnataka": {
    "label": "Karnataka State HE Council",
    "url": "https://kshec.karnataka.gov.in/"
  },
  "Kerala": {
    "label": "Kerala State Higher Education Council",
    "url": "https://kshec.kerala.gov.in/"
  },
  "Ladakh": {
    "label": "University of Ladakh",
    "url": "https://www.uoladakh.ac.in/"
  },
  "Madhya Pradesh": {
    "label": "MP Higher Education Department",
    "url": "https://highereducation.mp.gov.in/"
  },
  "Maharashtra": {
    "label": "Maharashtra HE Department",
    "url": "https://highereducation.maharashtra.gov.in/"
  },
  "Manipur": {
    "label": "Manipur Higher Education Directorate",
    "url": "https://dhemanipur.gov.in/"
  },
  "Meghalaya": {
    "label": "Meghalaya Education Department",
    "url": "https://megeducation.gov.in/"
  },
  "Mizoram": {
    "label": "Mizoram Higher Education Directorate",
    "url": "https://dhemizoram.edu.in/"
  },
  "Nagaland": {
    "label": "Nagaland University",
    "url": "https://www.nagalanduniversity.ac.in/"
  },
  "Odisha": {
    "label": "Odisha State Higher Education Council",
    "url": "https://shec.odisha.gov.in/"
  },
  "Puducherry": {
    "label": "Pondicherry University",
    "url": "https://www.pondiuni.edu.in/"
  },
  "Punjab": {
    "label": "Punjab State Higher Education Council",
    "url": "https://pshec.punjab.gov.in/"
  },
  "Rajasthan": {
    "label": "Rajasthan Higher Education Department",
    "url": "https://highereducation.rajasthan.gov.in/"
  },
  "Sikkim": {
    "label": "Sikkim University",
    "url": "https://www.sikkimuniversity.ac.in/"
  },
  "Tamil Nadu": {
    "label": "Tamil Nadu Higher Education Directorate",
    "url": "https://www.tn.gov.in/dhe"
  },
  "Telangana": {
    "label": "Telangana Education Department",
    "url": "https://education.telangana.gov.in/"
  },
  "Tripura": {
    "label": "Tripura Higher Education Directorate",
    "url": "https://dhe.tripura.gov.in/"
  },
  "Uttar Pradesh": {
    "label": "UP Higher Education Council",
    "url": "https://uphec.up.nic.in/"
  },
  "Uttarakhand": {
    "label": "Uttarakhand Higher Education Department",
    "url": "https://ukhed.uk.gov.in/"
  },
  "West Bengal": {
    "label": "WB Higher Education Department",
    "url": "https://wbhed.gov.in/"
  },
  "Andaman & Nicobar": {
    "label": "A & N Administration \u2014 Education",
    "url": "https://www.and.nic.in/"
  },
  "Dadra & Nagar Haveli and Daman & Diu": {
    "label": "UGC Official Website",
    "url": "https://www.ugc.gov.in/"
  },
  "Lakshadweep": {
    "label": "UGC Official Website",
    "url": "https://www.ugc.gov.in/"
  }
};

const FYUGP_DATA = [
  {
    "id": 34,
    "state_name": "Andaman & Nicobar",
    "category": "Union Territory",
    "implementation_status": "Unknown",
    "summary": "Colleges affiliated to Pondicherry University (adopted FYUGP 2023). No separate UT-level policy. Implementation through affiliating university framework. [Status reclassified: no verifiable source articles found.]",
    "notified_year": "",
    "notified_semester": "",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Affiliated to Pondicherry University (FYUGP adopted 2023).",
    "universities": [
      {
        "name": "Andaman College / JNRM",
        "year": "2023",
        "type": "Affiliated to Pondicherry University (FYUGP through affiliating university)"
      }
    ],
    "timeline": [],
    "articles": []
  },
  {
    "id": 1,
    "state_name": "Andhra Pradesh",
    "category": "State",
    "implementation_status": "Unknown",
    "summary": "Andhra, Acharya Nagarjuna, and Sri Venkateswara universities piloting since 2022. Phased expansion continues through 2024. Three-language formula adopted alongside FYUGP. [Status reclassified: no verifiable source articles found.]",
    "notified_year": "",
    "notified_semester": "Academic Year 2022-23",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "One of the earliest states to implement across all universities simultaneously.",
    "universities": [
      {
        "name": "Acharya Nagarjuna University",
        "year": "2022",
        "type": "State University"
      },
      {
        "name": "Andhra University",
        "year": "2022",
        "type": "State University"
      },
      {
        "name": "Sri Venkateswara University",
        "year": "2022",
        "type": "State University"
      }
    ],
    "timeline": [
      {
        "date": "2022",
        "type": "Pilot",
        "desc": "AP State HE Council initiates FYUGP pilot across major universities"
      },
      {
        "date": "2024",
        "type": "Pilot",
        "desc": "Phased rollout continues with Andhra University, SVU, ANU"
      }
    ],
    "articles": []
  },
  {
    "id": 2,
    "state_name": "Arunachal Pradesh",
    "category": "State",
    "implementation_status": "Unknown",
    "summary": "No verifiable source articles found confirming FYUGP implementation in Arunachal Pradesh.",
    "notified_year": "",
    "notified_semester": "Academic Year 2023-24",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Adoption is primarily driven by central university directives.",
    "universities": [
      {
        "name": "Rajiv Gandhi University",
        "year": "2023",
        "type": "Central University"
      }
    ],
    "timeline": [
      {
        "date": "2023",
        "type": "Pilot",
        "desc": "Rajiv Gandhi University adopts FYUGP per central mandate"
      },
      {
        "date": "2024",
        "type": "Draft",
        "desc": "State-level FYUGP policy under consultation"
      }
    ],
    "articles": []
  },
  {
    "id": 3,
    "state_name": "Assam",
    "category": "State",
    "implementation_status": "Pilot / Phased Rollout",
    "summary": "Gauhati and Dibrugarh (state) plus Tezpur and Assam University (central) piloting since 2023. Full statewide rollout not yet achieved.",
    "notified_year": "2023",
    "notified_semester": "Academic Year 2023-24",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Full state-wide adoption with curriculum framework notified.",
    "universities": [
      {
        "name": "Dibrugarh University",
        "year": "2023",
        "type": "State University"
      },
      {
        "name": "Gauhati University",
        "year": "2023",
        "type": "State University"
      },
      {
        "name": "Tezpur University",
        "year": "2023",
        "type": "Central University"
      },
      {
        "name": "Assam University, Silchar",
        "year": "2024",
        "type": "Central University"
      }
    ],
    "timeline": [
      {
        "date": "2023",
        "type": "Pilot",
        "desc": "Tezpur University (central) adopts FYUGP"
      },
      {
        "date": "2024",
        "type": "Pilot",
        "desc": "Gauhati and Dibrugarh universities begin phased rollout"
      }
    ],
    "articles": []
  },
  {
    "id": 4,
    "state_name": "Bihar",
    "category": "State",
    "implementation_status": "Pilot / Phased Rollout",
    "summary": "PPU (Patna) set up task force to implement NEP 2020. Some universities began preparations for UG admissions under NEP. However, state govt also expressed inability to implement four-year programme. Mixed implementation. [Source: Times of India, Organiser]",
    "notified_year": "2023",
    "notified_semester": "Partial since 2023",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Mixed implementation - central universities leading, state universities catching up.",
    "universities": [
      {
        "name": "Patna University",
        "year": "2023",
        "type": "State University"
      },
      {
        "name": "Nalanda Open University",
        "year": "2024",
        "type": "State University"
      }
    ],
    "timeline": [
      {
        "date": "2024",
        "type": "Pilot",
        "desc": "Patna University, Nalanda Open University start FYUGP pilot"
      }
    ],
    "articles": []
  },
  {
    "id": 32,
    "state_name": "Chandigarh",
    "category": "Union Territory",
    "implementation_status": "Live / Fully Adopted",
    "summary": "Panjab University cleared 3-year degree option without exit for 4-year UG honours. Regulations approved for 4-year UG courses at PU-affiliated colleges. NEP being implemented in phased manner. [Source: Times of India, The Tribune, Hindustan Times]",
    "notified_year": "2022",
    "notified_semester": "Academic Year 2022-23",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Follows Punjab/central pattern.",
    "universities": [
      {
        "name": "Panjab University",
        "year": "2022",
        "type": "Central University"
      }
    ],
    "timeline": [
      {
        "date": "2022",
        "type": "Full Implementation",
        "desc": "Panjab University adopts FYUGP as central university"
      }
    ],
    "articles": []
  },
  {
    "id": 5,
    "state_name": "Chhattisgarh",
    "category": "State",
    "implementation_status": "Pilot / Phased Rollout",
    "summary": "NEP 2020 to be implemented across all universities in CG from 2024-25 session. Guru Ghasidas Vishwavidyalaya (central) and state universities included. [Source: thehitavada.com, 2024]",
    "notified_year": "2024",
    "notified_semester": "",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Implementation primarily at central institutions.",
    "universities": [
      {
        "name": "Guru Ghasidas Vishwavidyalaya",
        "year": "2023",
        "type": "State University"
      },
      {
        "name": "Bastar University",
        "year": "2024",
        "type": "State University"
      },
      {
        "name": "Pandit Ravishankar Shukla University",
        "year": "2024",
        "type": "State University"
      }
    ],
    "timeline": [
      {
        "date": "2023",
        "type": "Pilot",
        "desc": "Guru Ghasidas University (central) adopts FYUGP"
      },
      {
        "date": "2024",
        "type": "Draft",
        "desc": "State HE department drafts FYUGP implementation framework"
      }
    ],
    "articles": []
  },
  {
    "id": 35,
    "state_name": "Dadra & Nagar Haveli and Daman & Diu",
    "category": "Union Territory",
    "implementation_status": "Unknown",
    "summary": "Limited higher education infrastructure. No data available on FYUGP implementation.",
    "notified_year": "",
    "notified_semester": "",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Data unavailable.",
    "universities": [],
    "timeline": [],
    "articles": []
  },
  {
    "id": 29,
    "state_name": "Delhi",
    "category": "Union Territory",
    "implementation_status": "Live / Fully Adopted",
    "summary": "DU (pilot 2022, full 2023), JNU, and Jamia all adopted. Multiple entry/exit operational. Serves as national template for FYUGP.",
    "notified_year": "2022",
    "notified_semester": "Academic Year 2022-23",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "DU's FYUGP model has served as a template for other universities nationally.",
    "universities": [
      {
        "name": "Delhi University",
        "year": "2022",
        "type": "Central University"
      },
      {
        "name": "JNU",
        "year": "2023",
        "type": "Central University"
      },
      {
        "name": "Jamia Millia Islamia",
        "year": "2023",
        "type": "Central University"
      }
    ],
    "timeline": [
      {
        "date": "2022",
        "type": "Pilot",
        "desc": "Delhi University launches FYUGP pilot"
      },
      {
        "date": "2023",
        "type": "Full Implementation",
        "desc": "DU fully rolls out FYUGP across all colleges"
      }
    ],
    "articles": []
  },
  {
    "id": 6,
    "state_name": "Goa",
    "category": "State",
    "implementation_status": "Live / Fully Adopted",
    "summary": "Goa University adopted 2023 with full implementation. Multiple entry/exit and choice-based credit system in place.",
    "notified_year": "2023",
    "notified_semester": "Academic Year 2023-24",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Small state with a single major university - complete adoption.",
    "universities": [
      {
        "name": "Goa University",
        "year": "2023",
        "type": "State University"
      }
    ],
    "timeline": [
      {
        "date": "2023",
        "type": "Full Implementation",
        "desc": "Goa University adopts FYUGP with multiple entry/exit options"
      }
    ],
    "articles": []
  },
  {
    "id": 7,
    "state_name": "Gujarat",
    "category": "State",
    "implementation_status": "Pilot / Phased Rollout",
    "summary": "Gujarat University delayed Honours degree rollout under NEP. State universities including Gujarat University, MSU Baroda implementing phased NEP adoption. [Source: Times of India, 2026]",
    "notified_year": "2023",
    "notified_semester": "Academic Year 2023-24",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Strong state-level coordination led to swift implementation.",
    "universities": [
      {
        "name": "Gujarat University",
        "year": "2023",
        "type": "State University"
      },
      {
        "name": "MSU Baroda",
        "year": "2023",
        "type": "State University"
      },
      {
        "name": "Sardar Patel University",
        "year": "2024",
        "type": "State University"
      },
      {
        "name": "Saurashtra University",
        "year": "2024",
        "type": "State University"
      }
    ],
    "timeline": [
      {
        "date": "2023",
        "type": "Pilot",
        "desc": "Gujarat University and MSU Baroda start FYUGP pilot"
      },
      {
        "date": "2024",
        "type": "Full Implementation",
        "desc": "Statewide FYUGP rollout across all universities"
      }
    ],
    "articles": []
  },
  {
    "id": 8,
    "state_name": "Haryana",
    "category": "State",
    "implementation_status": "Live / Fully Adopted",
    "summary": "MDU Rohtak and GJUS&T Hisar implemented since 2023. Full rollout 2024. Academic Bank of Credits integrated across all universities.",
    "notified_year": "2022",
    "notified_semester": "Pilot from 2022",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Phased approach - pilot first, then gradual expansion.",
    "universities": [
      {
        "name": "Guru Jambheshwar University of Science & Technology, Hisar",
        "year": "2023",
        "type": "State University"
      },
      {
        "name": "Maharshi Dayanand University (MDU), Rohtak",
        "year": "2023",
        "type": "State University"
      }
    ],
    "timeline": [
      {
        "date": "2023",
        "type": "Pilot",
        "desc": "Kurukshetra University, MDU Rohtak start FYUGP"
      },
      {
        "date": "2024",
        "type": "Full Implementation",
        "desc": "Statewide FYUGP implementation with ABC integration"
      }
    ],
    "articles": []
  },
  {
    "id": 9,
    "state_name": "Himachal Pradesh",
    "category": "State",
    "implementation_status": "Pilot / Phased Rollout",
    "summary": "HPU to implement NEP-2020 from next academic session per VC announcement. Implementation faces challenges due to infrastructure and geographic constraints. [Source: Outlook India, The Tribune, 2023-2025]",
    "notified_year": "2022",
    "notified_semester": "Academic Year 2022-23",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Early adopter among northern states.",
    "universities": [
      {
        "name": "HP University, Shimla",
        "year": "2022",
        "type": "State University"
      }
    ],
    "timeline": [
      {
        "date": "2022",
        "type": "Pilot",
        "desc": "HP University Shimla starts FYUGP pilot"
      },
      {
        "date": "2024",
        "type": "Full Implementation",
        "desc": "Statewide rollout of FYUGP"
      }
    ],
    "articles": []
  },
  {
    "id": 30,
    "state_name": "Jammu & Kashmir",
    "category": "Union Territory",
    "implementation_status": "Pilot / Phased Rollout",
    "summary": "Kashmir and Jammu universities piloting since 2023. Gradual expansion to affiliated colleges. Infrastructure and capacity constraints persist.",
    "notified_year": "2023",
    "notified_semester": "Partial from 2023",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Gradual implementation underway.",
    "universities": [
      {
        "name": "University of Jammu",
        "year": "2023",
        "type": "State University"
      },
      {
        "name": "University of Kashmir",
        "year": "2023",
        "type": "State University"
      }
    ],
    "timeline": [
      {
        "date": "2023",
        "type": "Pilot",
        "desc": "University of Kashmir and University of Jammu pilot FYUGP"
      },
      {
        "date": "2024",
        "type": "Pilot",
        "desc": "Gradual expansion to affiliated colleges"
      }
    ],
    "articles": []
  },
  {
    "id": 10,
    "state_name": "Jharkhand",
    "category": "State",
    "implementation_status": "Pilot / Phased Rollout",
    "summary": "Ranchi, Vinoba Bhave, and Kolhan universities piloting since 2023-24 in select colleges. State government announced NEP implementation.",
    "notified_year": "2023",
    "notified_semester": "Partial from 2023",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Urban universities adopted; rural colleges lagging.",
    "universities": [
      {
        "name": "Kolhan University",
        "year": "2024",
        "type": "State University"
      },
      {
        "name": "Vinoba Bhave University",
        "year": "2024",
        "type": "State University"
      }
    ],
    "timeline": [
      {
        "date": "2023",
        "type": "Pilot",
        "desc": "Ranchi University starts FYUGP in select colleges"
      },
      {
        "date": "2024",
        "type": "Pilot",
        "desc": "State govt announces NEP implementation; Vinoba Bhave, Kolhan join"
      }
    ],
    "articles": []
  },
  {
    "id": 11,
    "state_name": "Karnataka",
    "category": "State",
    "implementation_status": "Live / Fully Adopted",
    "summary": "First mover. Bangalore, Mysore, Mangalore universities adopted 2021. Mandated across all 40+ state universities by 2024 with major/minor curriculum.",
    "notified_year": "2021",
    "notified_semester": "Academic Year 2021-22",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Pioneer state - first to implement NEP undergraduate framework fully.",
    "universities": [
      {
        "name": "Bangalore University",
        "year": "2021",
        "type": "State University"
      },
      {
        "name": "Mangalore University",
        "year": "2021",
        "type": "State University"
      },
      {
        "name": "University of Mysore",
        "year": "2021",
        "type": "State University"
      }
    ],
    "timeline": [
      {
        "date": "2021",
        "type": "Pilot",
        "desc": "Bangalore University starts FYUGP pilot"
      },
      {
        "date": "2024",
        "type": "Full Implementation",
        "desc": "State govt mandates FYUGP across all 40+ state universities"
      }
    ],
    "articles": []
  },
  {
    "id": 12,
    "state_name": "Kerala",
    "category": "State",
    "implementation_status": "Live / Fully Adopted",
    "summary": "Initially cautious but rolled out 2024-25 with Kerala-specific framework. Kerala, MG, Calicut, Kannur universities adopted. 3-year degree remains default exit; 4th year optional for honours.",
    "notified_year": "2024",
    "notified_semester": "Academic Year 2024-25",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Deliberate rollout after extensive consultation; later than some states but comprehensive.",
    "universities": [
      {
        "name": "Calicut University",
        "year": "2024",
        "type": "State University"
      },
      {
        "name": "Kannur University",
        "year": "2024",
        "type": "State University"
      },
      {
        "name": "MG University, Kottayam",
        "year": "2024",
        "type": "State University"
      },
      {
        "name": "University of Kerala",
        "year": "2024",
        "type": "State University"
      }
    ],
    "timeline": [
      {
        "date": "2024",
        "type": "Full Implementation",
        "desc": "Kerala rolls out FYUGP with state-adapted framework: 3-year degree default, 4th year optional for honours/research"
      }
    ],
    "articles": []
  },
  {
    "id": 31,
    "state_name": "Ladakh",
    "category": "Union Territory",
    "implementation_status": "Unknown",
    "summary": "University of Ladakh exploring adoption since 2024. Significant infrastructure and capacity constraints. No rollout yet. [Status reclassified: no verifiable source articles found.]",
    "notified_year": "",
    "notified_semester": "",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Nascent higher education infrastructure.",
    "universities": [
      {
        "name": "University of Ladakh",
        "year": "2024",
        "type": "State University"
      }
    ],
    "timeline": [
      {
        "date": "2024",
        "type": "Draft",
        "desc": "University of Ladakh exploring FYUGP adoption"
      }
    ],
    "articles": []
  },
  {
    "id": 36,
    "state_name": "Lakshadweep",
    "category": "Union Territory",
    "implementation_status": "Unknown",
    "summary": "Very limited higher education institutions. No data on FYUGP implementation.",
    "notified_year": "",
    "notified_semester": "",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Data unavailable.",
    "universities": [],
    "timeline": [],
    "articles": []
  },
  {
    "id": 13,
    "state_name": "Madhya Pradesh",
    "category": "State",
    "implementation_status": "Unknown",
    "summary": "Early mover. Devi Ahilya, Barkatullah, Jiwaji, and Dr Hari Singh Gour universities adopted 2022. Statewide mandate from 2023-24. [Status reclassified: no verifiable source articles found.]",
    "notified_year": "",
    "notified_semester": "Academic Year 2022-23",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Early state-wide adoption with centralized coordination.",
    "universities": [
      {
        "name": "Barkatullah University",
        "year": "2022",
        "type": "State University"
      },
      {
        "name": "Devi Ahilya Vishwavidyalaya",
        "year": "2022",
        "type": "State University"
      },
      {
        "name": "Dr. Hari Singh Gour University",
        "year": "2022",
        "type": "State University"
      },
      {
        "name": "Jiwaji University",
        "year": "2022",
        "type": "State University"
      }
    ],
    "timeline": [
      {
        "date": "2022",
        "type": "Pilot",
        "desc": "MP HE Dept mandates FYUGP pilot in select universities"
      },
      {
        "date": "2023",
        "type": "Full Implementation",
        "desc": "Statewide FYUGP implementation across all universities"
      }
    ],
    "articles": []
  },
  {
    "id": 14,
    "state_name": "Maharashtra",
    "category": "State",
    "implementation_status": "Live / Fully Adopted",
    "summary": "Mumbai, SPPU Pune, Shivaji, and Nagpur universities adopted 2023-24. HE Department GR mandating FYUGP issued. Some colleges raised infrastructure concerns.",
    "notified_year": "2023",
    "notified_semester": "Phased from 2023",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Phased approach due to large number of affiliated colleges.",
    "universities": [
      {
        "name": "Savitribai Phule Pune University",
        "year": "2023",
        "type": "State University"
      },
      {
        "name": "University of Mumbai",
        "year": "2023",
        "type": "State University"
      },
      {
        "name": "RTM Nagpur University",
        "year": "2024",
        "type": "State University"
      },
      {
        "name": "Shivaji University",
        "year": "2024",
        "type": "State University"
      }
    ],
    "timeline": [
      {
        "date": "2023",
        "type": "Pilot",
        "desc": "SPPU and Mumbai University start FYUGP pilot"
      },
      {
        "date": "2024",
        "type": "Full Implementation",
        "desc": "HE Dept issues GR mandating FYUGP across state"
      }
    ],
    "articles": []
  },
  {
    "id": 15,
    "state_name": "Manipur",
    "category": "State",
    "implementation_status": "Limited / Select Universities",
    "summary": "Central University of Manipur adopted 2023. State universities have not adopted. Law and order challenges slowed education policy rollout.",
    "notified_year": "2023",
    "notified_semester": "Partial from 2023",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Limited to central university directives.",
    "universities": [
      {
        "name": "Central University of Manipur",
        "year": "2024",
        "type": "Central University"
      }
    ],
    "timeline": [
      {
        "date": "2023",
        "type": "Pilot",
        "desc": "Central University of Manipur adopts FYUGP"
      },
      {
        "date": "2024",
        "type": "Draft",
        "desc": "State-level FYUGP policy under discussion"
      }
    ],
    "articles": []
  },
  {
    "id": 16,
    "state_name": "Meghalaya",
    "category": "State",
    "implementation_status": "Limited / Select Universities",
    "summary": "NEHU (central) adopted 2023. State-level policy being formulated. Most colleges are affiliated to NEHU.",
    "notified_year": "2023",
    "notified_semester": "Limited from 2023",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Central university leads; state institutions still consulting.",
    "universities": [
      {
        "name": "North-Eastern Hill University (NEHU)",
        "year": "2023",
        "type": "Central University"
      }
    ],
    "timeline": [
      {
        "date": "2023",
        "type": "Pilot",
        "desc": "NEHU adopts FYUGP as central university"
      },
      {
        "date": "2024",
        "type": "Draft",
        "desc": "State-level implementation policy being formulated"
      }
    ],
    "articles": []
  },
  {
    "id": 17,
    "state_name": "Mizoram",
    "category": "State",
    "implementation_status": "Unknown",
    "summary": "Mizoram University (central) adopted 2023 under UGC directive. State policy not yet formulated. [Status reclassified: no verifiable source articles found.]",
    "notified_year": "",
    "notified_semester": "",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Minimal state-level adoption data.",
    "universities": [
      {
        "name": "Mizoram University",
        "year": "2023",
        "type": "Central University"
      }
    ],
    "timeline": [
      {
        "date": "2023",
        "type": "Pilot",
        "desc": "Mizoram University adopts FYUGP under UGC directive"
      }
    ],
    "articles": []
  },
  {
    "id": 18,
    "state_name": "Nagaland",
    "category": "State",
    "implementation_status": "Limited / Select Universities",
    "summary": "Nagaland University (central) adopted 2023. State exploring adoption. Limited university infrastructure slows progress.",
    "notified_year": "2023",
    "notified_semester": "",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Insufficient data on state-level rollout.",
    "universities": [
      {
        "name": "Nagaland University",
        "year": "2023",
        "type": "Central University"
      }
    ],
    "timeline": [
      {
        "date": "2023",
        "type": "Pilot",
        "desc": "Nagaland University adopts FYUGP as central institution"
      }
    ],
    "articles": []
  },
  {
    "id": 19,
    "state_name": "Odisha",
    "category": "State",
    "implementation_status": "Pilot / Phased Rollout",
    "summary": "Utkal, Ravenshaw, Sambalpur, and Berhampur universities piloting 2023-24. Curriculum restructuring ongoing. Full statewide adoption in progress.",
    "notified_year": "2023",
    "notified_semester": "Academic Year 2023-24",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Comprehensive state-wide adoption with skill integration.",
    "universities": [
      {
        "name": "Ravenshaw University",
        "year": "2023",
        "type": "State University"
      },
      {
        "name": "Utkal University",
        "year": "2023",
        "type": "State University"
      },
      {
        "name": "Berhampur University",
        "year": "2024",
        "type": "State University"
      },
      {
        "name": "Sambalpur University",
        "year": "2024",
        "type": "State University"
      }
    ],
    "timeline": [
      {
        "date": "2023",
        "type": "Pilot",
        "desc": "Utkal University, Ravenshaw University start FYUGP pilot"
      },
      {
        "date": "2024",
        "type": "Pilot",
        "desc": "Sambalpur University, Berhampur University join phased rollout"
      }
    ],
    "articles": []
  },
  {
    "id": 33,
    "state_name": "Puducherry",
    "category": "Union Territory",
    "implementation_status": "Unknown",
    "summary": "Pondicherry University (central) adopted 2023. State college adoption remains limited. Central university is primary FYUGP pathway. [Status reclassified: no verifiable source articles found.]",
    "notified_year": "",
    "notified_semester": "",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Central university compliance; local institutions unclear.",
    "universities": [
      {
        "name": "Pondicherry University",
        "year": "2023",
        "type": "State University"
      }
    ],
    "timeline": [
      {
        "date": "2023",
        "type": "Pilot",
        "desc": "Pondicherry University adopts FYUGP per UGC mandate"
      }
    ],
    "articles": []
  },
  {
    "id": 20,
    "state_name": "Punjab",
    "category": "State",
    "implementation_status": "Live / Fully Adopted",
    "summary": "Panjab, Guru Nanak Dev, and Punjabi universities adopted 2022. Full statewide rollout by 2024, expanded to affiliated colleges.",
    "notified_year": "2022",
    "notified_semester": "Academic Year 2022-23",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Strong implementation across major universities.",
    "universities": [
      {
        "name": "Guru Nanak Dev University",
        "year": "2022",
        "type": "State University"
      },
      {
        "name": "Panjab University",
        "year": "2022",
        "type": "Central University"
      },
      {
        "name": "Punjabi University, Patiala",
        "year": "2022",
        "type": "State University"
      }
    ],
    "timeline": [
      {
        "date": "2022",
        "type": "Pilot",
        "desc": "Panjab University, GNDU, Punjabi University start FYUGP"
      },
      {
        "date": "2024",
        "type": "Full Implementation",
        "desc": "Statewide FYUGP rollout across Punjab"
      }
    ],
    "articles": []
  },
  {
    "id": 21,
    "state_name": "Rajasthan",
    "category": "State",
    "implementation_status": "Live / Fully Adopted",
    "summary": "Rajasthan, Mohanlal Sukhadia, Kota, and Bikaner universities adopted 2023. Full state-wide implementation with major/minor/vocational curriculum.",
    "notified_year": "2023",
    "notified_semester": "Academic Year 2023-24",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "State-wide adoption with unified framework.",
    "universities": [
      {
        "name": "Bikaner University",
        "year": "2023",
        "type": "State University"
      },
      {
        "name": "Kota University",
        "year": "2023",
        "type": "State University"
      },
      {
        "name": "Mohanlal Sukhadia University",
        "year": "2023",
        "type": "State University"
      },
      {
        "name": "University of Rajasthan",
        "year": "2023",
        "type": "State University"
      }
    ],
    "timeline": [
      {
        "date": "2023",
        "type": "Full Implementation",
        "desc": "Rajasthan HE Dept mandates FYUGP across all state universities"
      }
    ],
    "articles": []
  },
  {
    "id": 22,
    "state_name": "Sikkim",
    "category": "State",
    "implementation_status": "Limited / Select Universities",
    "summary": "Sikkim University (central) adopted 2023. Sikkim Manipal (private) partial adoption in 2024. State policy under development.",
    "notified_year": "2023",
    "notified_semester": "Limited from 2023",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Central university adoption; state institutions unclear.",
    "universities": [
      {
        "name": "Sikkim University",
        "year": "2023",
        "type": "Central University"
      },
      {
        "name": "Sikkim Manipal University",
        "year": "2024",
        "type": "State University"
      }
    ],
    "timeline": [
      {
        "date": "2023",
        "type": "Pilot",
        "desc": "Sikkim University (central) adopts FYUGP"
      },
      {
        "date": "2024",
        "type": "Draft",
        "desc": "Sikkim Manipal University explores partial adoption"
      }
    ],
    "articles": []
  },
  {
    "id": 23,
    "state_name": "Tamil Nadu",
    "category": "State",
    "implementation_status": "Resisting / Not Adopted",
    "summary": "DMK govt opposes FYUGP; state universities maintain 3-year system. IIT Madras and NIT Trichy adopted 2023 as central institutions. Signs of softening in 2025.",
    "notified_year": "2023\u00b9",
    "notified_semester": "",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Most prominent state resisting NEP FYUGP as of early 2025.",
    "universities": [
      {
        "name": "Bharathiar University",
        "year": "",
        "type": "State University"
      },
      {
        "name": "Madurai Kamaraj University",
        "year": "",
        "type": "State University"
      },
      {
        "name": "University of Madras",
        "year": "",
        "type": "State University"
      },
      {
        "name": "IIT Madras",
        "year": "2023",
        "type": "State University"
      },
      {
        "name": "NIT Trichy",
        "year": "2023",
        "type": "State University"
      }
    ],
    "timeline": [
      {
        "date": "2022",
        "type": "Resistance",
        "desc": "TN DMK govt formally opposes NEP 2020 and FYUGP"
      },
      {
        "date": "2025",
        "type": "Potential Shift",
        "desc": "Signs of softening - select state universities explore pilots"
      }
    ],
    "articles": []
  },
  {
    "id": 24,
    "state_name": "Telangana",
    "category": "State",
    "implementation_status": "Pilot / Phased Rollout",
    "summary": "Telangana State universities to implement NEP 2020 from 2026\u201327. TGCHE urged universities to align with NEP reforms. [Source: Telangana Today, The Hindu, 2026]",
    "notified_year": "2026",
    "notified_semester": "Partial from 2023",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Mixed implementation across universities.",
    "universities": [
      {
        "name": "Kakatiya University",
        "year": "2023",
        "type": "State University"
      },
      {
        "name": "Osmania University",
        "year": "2023",
        "type": "State University"
      }
    ],
    "timeline": [
      {
        "date": "2023",
        "type": "Pilot",
        "desc": "Osmania University starts FYUGP in select colleges"
      },
      {
        "date": "2024",
        "type": "Pilot",
        "desc": "Kakatiya University begins phased FYUGP rollout"
      }
    ],
    "articles": []
  },
  {
    "id": 25,
    "state_name": "Tripura",
    "category": "State",
    "implementation_status": "Pilot / Phased Rollout",
    "summary": "Tripura to implement NEP in general degree colleges from 2023. Tripura University (central) adopted FYUGP. New courses introduced under NEP. [Source: Telegraph India, 2023; Borok Times, 2026]",
    "notified_year": "2023",
    "notified_semester": "",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Primarily central university compliance.",
    "universities": [
      {
        "name": "Tripura University",
        "year": "2023",
        "type": "Central University"
      }
    ],
    "timeline": [
      {
        "date": "2023",
        "type": "Pilot",
        "desc": "Tripura University (central) adopts FYUGP"
      }
    ],
    "articles": []
  },
  {
    "id": 26,
    "state_name": "Uttar Pradesh",
    "category": "State",
    "implementation_status": "Live / Fully Adopted",
    "summary": "BHU, Lucknow, Allahabad, and AMU adopted 2022. Pilot to full statewide by 2024-25. Largest student population \u2014 massive rollout.",
    "notified_year": "2022",
    "notified_semester": "Academic Year 2022-23",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Large-scale implementation across India's most populous state.",
    "universities": [
      {
        "name": "Aligarh Muslim University",
        "year": "2022",
        "type": "State University"
      },
      {
        "name": "Allahabad University",
        "year": "2022",
        "type": "State University"
      },
      {
        "name": "Banaras Hindu University (BHU)",
        "year": "2022",
        "type": "Central University"
      },
      {
        "name": "University of Lucknow",
        "year": "2022",
        "type": "State University"
      }
    ],
    "timeline": [
      {
        "date": "2022",
        "type": "Pilot",
        "desc": "UP starts FYUGP in select universities (BHU, Lucknow)"
      },
      {
        "date": "2023",
        "type": "Pilot",
        "desc": "Central universities in UP adopt FYUGP (BHU)"
      },
      {
        "date": "2024",
        "type": "Full Implementation",
        "desc": "Statewide FYUGP rollout across all universities"
      }
    ],
    "articles": []
  },
  {
    "id": 27,
    "state_name": "Uttarakhand",
    "category": "State",
    "implementation_status": "Unknown",
    "summary": "Doon, Uttarakhand Open, and Garhwal universities adopted 2023-24. Full statewide implementation from 2024. Government supportive of NEP. [Status reclassified: no verifiable source articles found.]",
    "notified_year": "",
    "notified_semester": "Academic Year 2023-24",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "Swift state-wide adoption.",
    "universities": [
      {
        "name": "Uttarakhand Open University",
        "year": "2023",
        "type": "State University"
      },
      {
        "name": "Doon University",
        "year": "2024",
        "type": "State University"
      },
      {
        "name": "Hemvati Nandan Bahuguna Garhwal University",
        "year": "2024",
        "type": "State University"
      }
    ],
    "timeline": [
      {
        "date": "2023",
        "type": "Pilot",
        "desc": "Kumaun University, Doon University start FYUGP pilot"
      },
      {
        "date": "2024",
        "type": "Full Implementation",
        "desc": "Statewide FYUGP implementation"
      }
    ],
    "articles": []
  },
  {
    "id": 28,
    "state_name": "West Bengal",
    "category": "State",
    "implementation_status": "Pilot / Phased Rollout",
    "summary": "Complex NEP relationship. Initially resisted, then implemented 4-year UG honours from 2023-24 in state colleges. Formed task force for NEP rollout. Later formulated own state education policy. [Source: The Hindu, livemint, Outlook India, 2023]",
    "notified_year": "2023",
    "notified_semester": "",
    "source_url_1": "",
    "source_url_2": "",
    "last_updated": "2026-08-16",
    "notes": "State govt has been cautious/ambivalent about full NEP adoption.",
    "universities": [
      {
        "name": "Jadavpur University",
        "year": "",
        "type": "State University"
      },
      {
        "name": "University of Calcutta",
        "year": "",
        "type": "State University"
      },
      {
        "name": "Visva-Bharati University",
        "year": "2023",
        "type": "Central University"
      }
    ],
    "timeline": [
      {
        "date": "2022",
        "type": "Resistance",
        "desc": "TMC govt expresses reservations about NEP implementation"
      },
      {
        "date": "2025",
        "type": "Pilot",
        "desc": "Some state universities begin exploring limited FYUGP pilots"
      }
    ],
    "articles": []
  }
];
